/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.birt.chart.model.donut.series.validation;


/**
 * A sample validator interface for {@link org.eclipse.birt.chart.model.donut.series.DonutSeries}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DonutSeriesValidator {
	boolean validate();

	boolean validateThickness(int value);
}
